version: '3.9'

services:
  mysql_payments:
    image: mysql:8.0-debian
    container_name: mysql_payments
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payments
    volumes:
      - data-mysql-payments:/var/lib/mysql
    restart: always
    networks:
      - microservices_network


volumes:
  data-mysql-payments:

networks:
  microservices_network:
    driver: bridge